# Generated by Django 2.2.6 on 2020-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_grps'),
    ]

    operations = [
        migrations.AddField(
            model_name='grps',
            name='gimg',
            field=models.ImageField(default='default.png', upload_to='GroupImg'),
        ),
    ]
